### ISSUE TITLE
你好 请问这个固件怎么开启ipv6？谢谢

### ISSUE THREAD

**Issue by xuanjinok** [huangqian8/Cloud-N1-OpenWrt#14]
你好 请问这个固件怎么开启ipv6？谢谢

**Comment by huangqian8** [comment]
没有测试环境，不支持ipv6。

**Comment by doskoi** [comment]
我添加了支持且测试过了，参考我的repo里的config.sh里所有ipv6相关的key

**Comment by xuanjinok** [comment]
谢谢 改天下载固件试一下

**Comment by doskoi** [comment]
对了，这样是开启了支持，但是默认配置里不包含。
你还需要添加一个新的网络接口：网络-添加网络接口
名字随便，比如：LAN6
协议：DHCPv6
包括以下接口：自定义接口，填入： @lan
