### ISSUE TITLE
请大佬加两个插件！！！！

### ISSUE THREAD

**Issue by sandaisi** [huangqian8/Cloud-N1-OpenWrt#18]
大佬能否增加晶晨宝盒或者文件传输插件？刚需啊！还有支持IPV6，就是接口协议中没有DHCPV6客户端，谢谢！！！

**Comment by huangqian8** [comment]
晶晨宝盒luci-app-amlogic是有的，其余的考虑后续更新中加入。

**Comment by sandaisi** [comment]
> 晶晨宝盒luci-app-amlogic是有的，其余的考虑后续更新中加入。

luci-app-amlogic系统里没有呀，软件包也找不到

**Comment by sandaisi** [comment]
> 晶晨宝盒luci-app-amlogic是有的，其余的考虑后续更新中加入。

用一件安装命令curl -fsSL git.io/luci-app-amlogic | bash缺少jq依赖

**Comment by huangqian8** [comment]
> > 晶晨宝盒luci-app-amlogic是有的，其余的考虑后续更新中加入。
> 
> 用一件安装命令curl -fsSL git.io/luci-app-amlogic | bash缺少jq依赖

脚本有些问题，也很久没更新了，打算稍后更新一下，把你的几个需求加上去。

**Comment by sandaisi** [comment]
感谢，感谢！！！

**Comment by huangqian8** [comment]
最新版已集成晶晨宝盒和文件传输插件。
ipv6也做了编译，但没有测试环境，你可以试一下。

**Comment by sandaisi** [comment]
> 最新版已集成晶晨宝盒和文件传输插件。
> ipv6也做了编译，但没有测试环境，你可以试一下。

大佬🐂啊！中午就去测试一下

**Comment by sandaisi** [comment]
> 最新版已集成晶晨宝盒和文件传输插件。
> ipv6也做了编译，但没有测试环境，你可以试一下。



大佬汇报一下测速结果:

1.已经安装晶晨宝盒(因插件无法安装及无法使用，未能测试)，文件传输(可上传ipk,无法安装，一直报错，无论安装什么插件都报错误，举个例子放最后);
2.hellowould插件无法使用，无法拉去节点，换了三个机场都不行;
3.原来的openclash、SSR、adgrud home、alist没了，希望加上;
以上就是测试结果，请知悉！









Unknown package 'alist'.

Collected errors:
 * opkg_conf_parse_file: Duplicate src declaration (openwrt_core https://mirrors.cloud.tencent.com/lede/snapshots/targets/armvirt/64/packages). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (openwrt_base https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_cortex-a53/base). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (openwrt_luci https://mirrors.cloud.tencent.com/lede/releases/18.06.9/packages/aarch64_cortex-a53/luci). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (openwrt_packages https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_cortex-a53/packages). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (openwrt_routing https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_cortex-a53/routing). Skipping.
 * opkg_conf_parse_file: Duplicate src declaration (openwrt_telephony https://mirrors.cloud.tencent.com/lede/snapshots/packages/aarch64_cortex-a53/telephony). Skipping.
 * pkg_hash_fetch_best_installation_candidate: Packages for alist found, but incompatible with the architectures configured
 * opkg_install_cmd: Cannot install package alist.

离线安装失败,错误码 255

**Comment by huangqian8** [comment]
1、文件传输的功能我得测试一下，因为之前也没用过，不太清楚其机制。
2、`Hello World` 的订阅功能经测试正常，可以订阅获取节点。
3、`OpenClash` 、`AdGuard Home` 后续加上。`SSR` 和 `Alist` 之前的版本里应该也没有集成过。考虑加个 `阿里云盘 WebDAV`。

**Comment by sandaisi** [comment]
> 1、文件传输的功能我得测试一下，因为之前也没用过，不太清楚其机制。
> 2、`Hello World` 的订阅功能经测试正常，可以订阅获取节点。
> 3、`OpenClash` 、`AdGuard Home` 后续加上。`SSR` 和 `Alist` 之前的版本里应该也没有集成过。考虑加个 `阿里云盘 WebDAV`。



我的helloworld无论换什么订阅都无法订阅成功，全是这玩意，同样的订阅链接在SSR就没问题，奇怪了！
![Screenshot_2023-05-25-10-48-27-33_fab32b241c9ab51b0e057c943b753947.jpg](https://github.com/huangqian8/Cloud-N1-OpenWrt/assets/79754051/dcda9032-b63d-40d7-b7e8-c2ba1d784ca5)

**Comment by huangqian8** [comment]
无法订阅vless节点，感觉是vssr插件自身的问题，这个我没办法了。
已经添加了OpenClash和AdGuard Home，等自动编译完成吧。
