### ISSUE TITLE
要是使用说明再详细一些，估计会很多人来用

### ISSUE THREAD

**Issue by VectorZhao** [huangqian8/Cloud-N1-OpenWrt#5]

**Comment by huangqian8** [comment]
本来就是方便自己编译自用的，没想着做推广。因为都是开源的所以放在上面。
老手更倾向于自己编译，新手其实直接下载刷机固件会更方便些。

个人觉得路由器固件真没必要更新那么频繁，稳定即可。

**Comment by VectorZhao** [comment]
> 本来就是方便自己编译自用的，没想着做推广。因为都是开源的所以放在上面。
> 老手更倾向于自己编译，新手其实直接下载刷机固件会更方便些。
> 
> 个人觉得路由器固件真没必要更新那么频繁，稳定即可。

有道理，没事折腾升级还挺麻烦
